# This file was generated by GoReleaser. DO NOT EDIT.
cask "testmesh" do
  name "testmesh"
  desc "E2E integration testing platform — YAML flows over HTTP, DB, Kafka, gRPC and more"
  homepage "https://testmesh.io"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "testmesh"

  on_macos do
    on_intel do
      url "https://github.com/test-mesh/testmesh/releases/download/v#{version}/testmesh_#{version}_macOS_amd64.tar.gz"
      sha256 "9102098754aacce9baf6e3430190a0747fef1baee037c954fbb7145d3f760794"
    end
    on_arm do
      url "https://github.com/test-mesh/testmesh/releases/download/v#{version}/testmesh_#{version}_macOS_arm64.tar.gz"
      sha256 "a6c82ce434a9d0f546e5e4cb991d4d75b384f38a03893bfd1dd988178df53526"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/test-mesh/testmesh/releases/download/v#{version}/testmesh_#{version}_linux_amd64.tar.gz"
      sha256 "7f0672e4b344bdbe50e376f32079c90172d4222f6edc40dd81226eae45bd93dd"
    end
    on_arm do
      url "https://github.com/test-mesh/testmesh/releases/download/v#{version}/testmesh_#{version}_linux_arm64.tar.gz"
      sha256 "f8868bd4f9f819e2f57280860dbf6e55db4042d29bb09c2251bc07e7718c35a4"
    end
  end

  # No zap stanza required
end
