# This file was generated by GoReleaser. DO NOT EDIT.
cask "testmesh" do
  name "testmesh"
  desc "E2E integration testing platform — YAML flows over HTTP, DB, Kafka, gRPC and more"
  homepage "https://testmesh.io"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "testmesh"

  on_macos do
    on_intel do
      url "https://github.com/test-mesh/testmesh/releases/download/v#{version}/testmesh_#{version}_macOS_amd64.tar.gz"
      sha256 "2648da16bbdb6342231cbff73c40ea82424e41ee893ac8739404d6ed2a01f49f"
    end
    on_arm do
      url "https://github.com/test-mesh/testmesh/releases/download/v#{version}/testmesh_#{version}_macOS_arm64.tar.gz"
      sha256 "860e530bfc50f990364882cdd5392b370c56998da22ec0bbfea1b3892eb0b949"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/test-mesh/testmesh/releases/download/v#{version}/testmesh_#{version}_linux_amd64.tar.gz"
      sha256 "272c664a356bc8d633bfbea7ad896db40a8a12a17e442b2e383a0d2d4071d3af"
    end
    on_arm do
      url "https://github.com/test-mesh/testmesh/releases/download/v#{version}/testmesh_#{version}_linux_arm64.tar.gz"
      sha256 "c8c727fcc7c02e1aab29aec3a19a7a140593f9f49b4c12534313d37881675aac"
    end
  end

  # No zap stanza required
end
