# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testmesh < Formula
  desc "E2E integration testing platform — YAML flows over HTTP, DB, Kafka, gRPC and more"
  homepage "https://testmesh.io"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/test-mesh/testmesh/releases/download/v0.1.9/testmesh_0.1.9_macOS_amd64.tar.gz"
      sha256 "550434c877fa0ac5eb478a4274e23dbb8f222f0e7fec4497c203088762d14c11"

      define_method(:install) do
        bin.install "testmesh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/test-mesh/testmesh/releases/download/v0.1.9/testmesh_0.1.9_macOS_arm64.tar.gz"
      sha256 "0a19b23cd81fd69b0ff4b99f79e67bf26b13bfec6dfa8c25240d77b0c01ba673"

      define_method(:install) do
        bin.install "testmesh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/test-mesh/testmesh/releases/download/v0.1.9/testmesh_0.1.9_linux_amd64.tar.gz"
      sha256 "1d1f5588ff112108609f1b950badb3a4efdabbbc137b0d80f273633abbf332a4"
      define_method(:install) do
        bin.install "testmesh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/test-mesh/testmesh/releases/download/v0.1.9/testmesh_0.1.9_linux_arm64.tar.gz"
      sha256 "b10a1c16f4a1d7886fbb643a084ee37cbe71471c8e7d12b612153b239c3b8a6f"
      define_method(:install) do
        bin.install "testmesh"
      end
    end
  end
end
