# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Testmesh < Formula
  desc "E2E integration testing platform — YAML flows over HTTP, DB, Kafka, gRPC and more"
  homepage "https://testmesh.io"
  version "0.1.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/test-mesh/testmesh/releases/download/v0.1.11/testmesh_0.1.11_macOS_amd64.tar.gz"
      sha256 "211fd9077b9d9c14d4df0360d44daaedeb4fdd3af2d4a6d85ddb232b894032c4"

      define_method(:install) do
        bin.install "testmesh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/test-mesh/testmesh/releases/download/v0.1.11/testmesh_0.1.11_macOS_arm64.tar.gz"
      sha256 "19b4b3e37d9e5912c31fdd158f4b602b6c6413638d2dc76658c43751c579ea61"

      define_method(:install) do
        bin.install "testmesh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/test-mesh/testmesh/releases/download/v0.1.11/testmesh_0.1.11_linux_amd64.tar.gz"
      sha256 "5b866ffb70e142bdaf3d5320de247049d7f6dac611b56ceb2d7a8a3e688325a2"
      define_method(:install) do
        bin.install "testmesh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/test-mesh/testmesh/releases/download/v0.1.11/testmesh_0.1.11_linux_arm64.tar.gz"
      sha256 "b72babc092c276459bfac42f7c0e156bc62cb42629b74b96b13471619f3865c3"
      define_method(:install) do
        bin.install "testmesh"
      end
    end
  end
end
